### ISSUE TITLE
Docker image is unnecessarily large

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep-action#106]
Our docker image is 388mb, but semgrep itself is <100MB and semgrep-agent is 100mb. We are adding a few dependnecies but we shouldn't be so large. This has a user impact because CI systems pull semgrep_agent so the smaller we are, the faster we run.

quick ideas:
- [ ] probably we don't need to use virtualenvs in the docker image, can just install as system deps?
- [ ] we waste 139MB in the line `COPY --from=semgrep /usr/local/bin/semgrep-core /tmp/semgrep-core` which we can't delete later because docker layers are append-only. Either squash the image, or maybe we just can just install semgrep from pip?

Some debugging:

```
ine@imbp4 ~/D/r/semgrep-action (develop)> docker image list
REPOSITORY                               TAG                  IMAGE ID            CREATED             SIZE
deleteme                                 latest               3a2024614c6b        59 seconds ago      388MB
```

```
ine@imbp4 ~/D/r/semgrep-action (develop) [1]> docker image history deleteme
IMAGE               CREATED              CREATED BY                                      SIZE                COMMENT
3a2024614c6b        About a minute ago   /bin/sh -c #(nop)  ENV SEMGREP_ACTION=true S…   0B
1248a8253a31        About a minute ago   /bin/sh -c #(nop)  CMD ["python" "-m" "semgr…   0B
ea96aab92e25        About a minute ago   /bin/sh -c #(nop)  ENV PATH=/root/.local/bin…   0B
5e31234a8ae2        About a minute ago   /bin/sh -c #(nop) COPY dir:1fd9cad476546e4a5…   117kB
880a9eeb1cb8        About a minute ago   /bin/sh -c apk add --no-cache --virtual=.bui…   207MB
f9731445eead        3 minutes ago        /bin/sh -c #(nop) COPY file:242636c2950567f1…   139MB
32b1ab530668        3 minutes ago        /bin/sh -c #(nop)  ENV INSTALLED_SEMGREP_VER…   0B
d085a20dee12        3 minutes ago        /bin/sh -c #(nop) COPY file:89f9fdac4917c31a…   597B
1866ac2367b4        3 minutes ago        /bin/sh -c #(nop) COPY file:c53eceb6b503d20b…   8.47kB
c061f1cc2db7        3 minutes ago        /bin/sh -c #(nop) WORKDIR /app                  0B
6b73b71fd64e        8 days ago           /bin/sh -c #(nop)  CMD ["python3"]              0B
<missing>           8 days ago           /bin/sh -c set -ex;   wget -O get-pip.py "$P…   7.24MB
<missing>           8 days ago           /bin/sh -c #(nop)  ENV PYTHON_GET_PIP_SHA256…   0B
<missing>           8 days ago           /bin/sh -c #(nop)  ENV PYTHON_GET_PIP_URL=ht…   0B
<missing>           3 weeks ago          /bin/sh -c #(nop)  ENV PYTHON_PIP_VERSION=20…   0B
<missing>           3 weeks ago          /bin/sh -c cd /usr/local/bin  && ln -s idle3…   32B
<missing>           3 weeks ago          /bin/sh -c set -ex  && apk add --no-cache --…   27.7MB
<missing>           3 weeks ago          /bin/sh -c #(nop)  ENV PYTHON_VERSION=3.7.9     0B
<missing>           3 weeks ago          /bin/sh -c #(nop)  ENV GPG_KEY=0D96DF4D4110E…   0B
<missing>           3 weeks ago          /bin/sh -c apk add --no-cache ca-certificates   512kB
<missing>           3 weeks ago          /bin/sh -c #(nop)  ENV LANG=C.UTF-8             0B
<missing>           3 weeks ago          /bin/sh -c #(nop)  ENV PATH=/usr/local/bin:/…   0B
<missing>           3 weeks ago          /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B
<missing>           3 weeks ago          /bin/sh -c #(nop) ADD file:f17f65714f703db90…   5.57MB
```

**Comment by underyx** [comment]
> we waste 139MB in the line COPY --from=semgrep /usr/local/bin/semgrep-core /tmp/semgrep-core which we can't delete later because docker layers are append-only. Either squash the image, or maybe we just can just install semgrep from pip?

But we need `semgrep-core` for semgrep to work at runtime. I don't think we lose any additional space during installation. We cannot directly install from pip cause the pip wheels don't (cannot) support Alpine linux.

**Comment by underyx** [comment]
> probably we don't need to use virtualenvs in the docker image, can just install as system deps?

We had dependency version conflicts between bento & semgrep a while ago, which is why we started doing this. I kinda like that semgrep-agent and semgrep have independent dependencies, one less thing to worry about when developing.

**Comment by ievans** [comment]
I chatted with @underyx and clarified some things:

> I was trying to say that that second install copies the 139MB into /root/.local/pipx if i understand correctly, so we don’t need the /tmp anymore. but the rm -rf /tmp is not reclaiming any space. b/c the docker layers are append only the rm -rf /tmp is useless. If you build with --squash you’ll reclaim it, but that’s an experimental flag

**Comment by mschwager** [comment]
Removing `PRECOMPILED_LOCATION` (https://github.com/returntocorp/semgrep-action/pull/156) took this down to `313MB` for me. Removing reliance on `pipx` brought it down to `291MB`. Should we remove `pipx` and call this done?

**Comment by ievans** [comment]
👍 from me @mschwager!

**Comment by raghavjain3** [comment]
Closing since the image [here](https://hub.docker.com/r/returntocorp/semgrep-agent) seems to be significantly smaller in size than a few months ago (60MB compressed instead of 100+MB). 

@ievans please feel free to reopen if you find this to still be an issue

**Comment by ievans** [comment]
brilliant work all!
