### ISSUE TITLE
clarify "not logged in" error message

### ISSUE THREAD

**Issue by sabrinabrogren** [returntocorp/sgrep-action#108]
Original "bug" report below, but check out the discussion for more relevant details to this ticket
# 
Sorry for the obscure title, I can't be much more descriptive because I'm not sure what's going on.

These were run within an hour of each other:
https://github.com/returntocorp/dry-runs/pull/7/checks
https://github.com/returntocorp/dry-runs/pull/8/checks

For some reason, it appears that when someone other than me tries to create a PR, semgrep errors out in CI with:
```
=== detecting environment
| versions    - semgrep 0.30.0 on Python 3.7.9
| environment - running in github-actions, triggering event is 'pull_request'
| semgrep.dev - not logged in
=== setting up agent configuration
Error: OR] you didn't configure what rules semgrep should scan for.
```

(the first few lines from running on my PR:)
```
=== detecting environment
| versions    - semgrep 0.30.0 on Python 3.7.9
| environment - running in github-actions, triggering event is 'pull_request'
| semgrep.dev - logged in as deployment #1
=== setting up agent configuration
| using semgrep rules configured on the web UI
```

The rules to scan for are just from the default policy, so they are not configured in `semgrep.yml`.

**Comment by underyx** [comment]
@sabihb PR #8 there has a source branch from a different, forked repo. GitHub blocks access to secrets for code that comes from external sources, i.e. forks. Their line of thinking is that @AzureUmbra's repository could have malicious code that prints out the SEMGREP_TOKEN to the CI logs, and thereby @AzureUmbra could steal r2c's secret token.

**Comment by sabrinabrogren** [comment]
Oh interesting, that makes sense! Then this is not an issue with semgrep-action at all. I wonder why it's making the source branch forked rather than the original repo.

**Comment by dlukeomalley** [comment]
@sabihb The bug here may be the error message then, which doesn't explain the missing token and/or offer clear next steps. I'd vote for keeping this open and renaming / restructuring, what do you think?

**Comment by underyx** [comment]
Yes, perhaps `not logged in` & `logged in as deployment #1` should be replaced with something that's… less of a lie. I chose this wording just cause I thought this'd be the most clear to someone who has no idea what semgrep.dev is.

**Comment by sabrinabrogren** [comment]
Maybe an error message that also suggests a fix might be helpful? Something like `not logged in - check SEMGREP-TOKEN configuration for this repo or organization`
