### ISSUE TITLE
Baseline-ref argument ignored in CI environment

### ISSUE THREAD

**Issue by Sjord** [returntocorp/sgrep-action#123]
The `--baseline-ref` is only used in [GitMeta](https://github.com/returntocorp/semgrep-action/blob/a0fd91323cdef3a67aa4eaae30db7cff5e68def8/src/semgrep_agent/meta.py#L60), and not in [GithubMeta](https://github.com/returntocorp/semgrep-action/blob/a0fd91323cdef3a67aa4eaae30db7cff5e68def8/src/semgrep_agent/meta.py#L148) or [GitlabMeta](https://github.com/returntocorp/semgrep-action/blob/a0fd91323cdef3a67aa4eaae30db7cff5e68def8/src/semgrep_agent/meta.py#L231). This means that semgrep-action will claim that all files are new, even when the `--baseline-ref` argument is given.

I expect `--baseline-ref` to override environment variables.

Running in GitLab CI:

```
$ python -m semgrep_agent --config /tmp/semgrep.yml --baseline-ref reviewed
=== detecting environment
| versions          - semgrep 0.32.0 on Python 3.7.9
| environment       - running in environment gitlab-ci, triggering event is 'push'
| manage            - not logged in
=== setting up agent configuration
| using semgrep rules from /tmp/semgrep.yml
| using default path ignore rules of common test and dependency directories
| found 911 files in the paths to be scanned
| skipping 43 files based on path ignore rules
=== looking for current issues in 868 files
| 20 current issues found
| No ignored issues found
| 20 current issues found
| No ignored issues found
=== not looking at pre-existing issues since all files with current issues are newly created
...
```

**Comment by underyx** [comment]
That's a very good point. Thanks for investigating the code to give us a super clear issue! We'll schedule this once the whole team's back after Thanksgiving :)
