### ISSUE TITLE
Fix PR merge result being compared to base branch in GHA

### ISSUE THREAD

**Issue by underyx** [returntocorp/sgrep-action#131]
the issue is with a surprising behavior of github: let’s assume you have this git history:

```
main branch  0--1--2--3--4--5
                 \
your branch       A--B
```

when github starts this job, it actually merges commit B into 5! that’s the codebase semgrep sees and our diff-aware scanning will compare “B merged into 5” against 1 to find new issues

so while you expect that only A and B’s changes will be scanned, right now it’s actually A, B, and 2 through 5 all being scanned, hence the additional changed file count

This might be the right one to use? But we still probably need to add python logic to fetch more commits for the baseline checkout to work https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit

**Comment by nbrahms** [comment]
Fix only worked in some cases, following up this afternoon.
