### ISSUE TITLE
Support Passing --severity Flag to semgrep

### ISSUE THREAD

**Issue by bflad** [returntocorp/sgrep-action#135]
## Description

Upstream `semgrep` in version 0.33.0 recently added a `--severity` flag that allows filtering rules to `WARNING`, etc. It would be fantastic if this project could support the ability to optionally configure that. As an example use case, we would love the ability to add rules within our codebase such as:

- Create rules with `WARNING` severity
- Incrementally fix existing reports over time due to time/effort
- Switch rule to `ERROR` severity when all existing reports are fixed

With the following logic in our CI configuration:

- Fail and report only `ERROR` severity rules on main branch pushes
- Fail and report `WARNING` and `ERROR` severity rules during pull request submission so new code can be fixed before going in

Happy to provide more details or submit an implementation if pointed in the right direction! Thanks!

## References

- https://github.com/returntocorp/semgrep/issues/1509
- https://github.com/returntocorp/semgrep/pull/2133
- https://github.com/returntocorp/semgrep/releases/tag/v0.33.0

**Comment by dlukeomalley** [comment]
@bflad This is a timely message. I'm in the midst of writing a proposal for better `info`, `warn`, and `error` result behavior. May I follow-up next week to get your feedback on what I'm working on?

**Comment by bflad** [comment]
@dlukeomalley sounds great, thank you!

**Comment by ankush** [comment]
Any progress was made on this? :thinking:

**Comment by fcsonline** [comment]
Do we have news about this?

**Comment by ievans** [comment]
@ankush @fcsonline @bflad @msorens @jack-om

sorry for the delay in comms! We just finished a long-running project to port semgrep-action into Semgrep itself.

as of Semgrep 0.86.5, all semgrep-action functionality now lives in Semgrep CLI itself so there is full flag support parity. Let me know if you have any issues!
