### ISSUE TITLE
[discussion] Should semgrepdep go in this repo?

### ISSUE THREAD

**Issue by underyx** [returntocorp/sgrep-action#145]
## Background

@ievans made a fork of semgrep-action that can also scan changes of yarn.lock etc. and post about how the dependency security hotspots have changed.

## Reasons for adding this feature here

From a technical standpoint this feature is pretty well separated, so I'm not worried about unclean code. A wider feature set would also mean the same project would be useful for more people. Some might discover the Semgrep action by looking for a cool dependency change analysis tool.

## Reasons against

I think it would lead to a branding nightmare though. Semgrepdep users would expect more support than we'd give it, semgrep-action users would be confused by a weird, unnatural option in the action's config. Users of both would still need to add separate workflows (like we did internally), which is also confusing to maintain since looking at a GHA overview you'd just see 'semgrep-action' running twice.

**Comment by ievans** [comment]
Another reason to put it here is that we've done a great job building a class that can grab metadata from Github, Gitlab, Jenkins, etc. So there's really only a few LoC for semgrepdep that are different. But it might be better to put all that into some kind of library?
