### ISSUE TITLE
Gracefully handle broken rules

### ISSUE THREAD

**Issue by minusworld** [returntocorp/sgrep-action#149]
Options:
- add a configuration option for "Failing Open" and "Failing Closed"
- continue Semgrep run in spite of broken rules and intelligently and clearly report the issue with a given rule

**Comment by nbrahms** [comment]
@minusworld I think this actually needs to be fixed in Semgrep itself, not the action.

The existing ticket for this is https://github.com/returntocorp/semgrep/issues/2152.

**Comment by brendongo** [comment]
Closed by https://github.com/returntocorp/semgrep-action/pull/172
