### ISSUE TITLE
latest semgrep-agent never completes its run

### ISSUE THREAD

**Issue by msorens** [returntocorp/sgrep-action#152]
Sometime between Thursday and Saturday, semgrep-agent started exceeding the 20-minute timeout in my CI system (Buildkite). Prior to this, it used to take anywhere from 30 seconds to 2 minutes.

I am using the `returntocorp/semgrep-agent:v1` docker image and the `v1` tag was updated with a new docker image yesterday just prior to my first failing build:
https://hub.docker.com/layers/returntocorp/semgrep-agent/v1/images/sha256-93d7382e52[…]0d0aaf8c42f48ff9decc28950974cf038d7a9a201d405?context=explore

Here is what I know:

1. All runs were 2 minutes or less until this past Thursday; now all runs are timing out.
2. All runs used semgrep 0.35.0 on Python 3.7.9. (That is, semgrep-agent on Thursday reported this version and the newer semgrep-agent today reports the same version, leading me to believe the issue is in semgrep-agent code rather than semgrep code.)
3. All runs used differential mode (--baseline-ref).
4. All runs were scanning a very small number of files, anywhere from zero to a couple dozen files being scanned. (The zero is due to how I have done some configuration; it is an item on my TODO list but not relevant to this issue.)
5. All runs used your standard docker image (returntocorp/semgrep-agent:v1) though of course the reference of that tag changes frequently.
6. I had only recently expanded the number of rulesets in my policy. I just tried reducing the policy size by going back to just the single r2c-ci ruleset (reducing rule count from 508 to 119) but no difference--semgrep-agent still timing out.

This same behavior occurs both in Buildkite and on the command-line when I run it locally. Also, my repository is open-source, so you can use my actual data to observe the problem.

The repo is here: https://github.com/chef/automate

And here are the bits from my Makefile:
```
SEMGREP_CONTAINER := returntocorp/semgrep-action:v1
SEMGREP_COMMON_PARAMS := -m semgrep_agent --publish-token ${SEMGREP_TOKEN} --publish-deployment ${SEMGREP_ID}
SEMGREP_REPO := --env SEMGREP_REPO_NAME=chef/automate
DOCKER_PARAMS := --volume $(realpath .):/automate --workdir /automate

semgrep: ## runs differential semgrep, checking only changes in the current PR, just as is done in CI
	docker run -it --rm --init $(DOCKER_PARAMS) $(SEMGREP_REPO) $(SEMGREP_CONTAINER) python $(SEMGREP_COMMON_PARAMS) --baseline-ref master
```

Implementation details:
1. When run on a git branch, there will be a non-zero number of files. When run on master, though, there will be zero files. But either way, the same problem occurs--semgrep-agent gets stuck. 
2. In Buildkite, semgrep-agent times out at about 20 minutes; on the command-line, I have been letting it run while I wrote this up, so it will not time-out. Thus far, it has run for 40 minutes and is still running. This is on a branch with 32 (rather ordinary) files.

Priority: High
I have had to completely disable semgrep-agent until this can be resolved.

**Comment by msorens** [comment]
@chmccreery rolled back the latest commit yesterday and the problem went away.
I am holding off re-instating semgrep-agent in my CI pipeline pending your investigation of this issue. (I am presuming you will likely try some fix and then I can try it manually, so it does not impact my CI pipeline.)

**Comment by nbrahms** [comment]
I root-caused this issue.

`shlex.split(None)` in Python 3.7 causes `shlex` to wait on standard input, thus hanging the process. Reverting the line that added `shlex.split(...)` on an optional command-line argument via #153 thus fixed this problem.

That said, we still need to add integration testing to prevent this form of regression in the future.
