### ISSUE TITLE
Disambiguate action/agent release names

### ISSUE THREAD

**Issue by underyx** [returntocorp/sgrep-action#158]
Confusing things right now:

1. Why is there an 'action' and a separate 'agent'?
1. How do you find the agent's code? How come it's in the action repo?
1. Why is the stable docker image tagged `:v1` instead of `:stable`?
1. What is `agent` even supposed to mean anyway? Why not `semgrep-ci`?
1. What is the release cadence of the image?
1. How do you pin a semgrep-agent version?
1. How do you get the agent outside Docker? Why is there an old PyPI package?
1. How can one go from running a CI job to running the same job locally?
1. How is this software connected to the semgrep.dev website?

@dlukeomalley am I missing anything else?

**Comment by msorens** [comment]
@underyx Nice idea here!

1. You mentioned how to run agent outside of Docker, but also useful to document how to run it with Docker for more stability and consistency when reporting bugs, for example. As you know, took me some effort to figure out the command to feed to Docker.

2. Not sure if this is in scope here, but might explain how agent is the gateway to the dashboard.

3. Suggest change your bulleted list above to a numbered list; makes it a lot easier for folks to talk about individual points. 😁

**Comment by underyx** [comment]
All good points! Especially number three :D I've updated the original post.
