### ISSUE TITLE
Make it safe to assume semgrep passing in PR means passing post merge

### ISSUE THREAD

**Issue by brendongo** [returntocorp/sgrep-action#181]
For a git tree below:
```
	  A---B---C pull-request
	 /
    D---E---F---G main
```
After the pull request is merged the tree will look like 
```
	  A---B---C pull-request
	 /          \
    D---E---F---G---H main
```
When we run semgrep-action on a github pull request we compare the code at C to D when we should be comparing H to G. 
 
Relevant slack convo:
<img width="524" alt="Screen Shot 2021-02-01 at 3 53 52 PM" src="https://user-images.githubusercontent.com/6498855/106532795-b68ce300-64a5-11eb-9b02-8ee5a3be0926.png">

Relevant comments in https://github.com/returntocorp/semgrep-action/pull/132

**Comment by dlukeomalley** [comment]
@brendongo Relatedly, I've gotten some requests to revive Bento's "baseline" scan functionality in `semgrep-agent`, so we can declare issue bankruptcy and focus on new stuff coming in.
