### ISSUE TITLE
'cryptography' package requires a Rust compiler

### ISSUE THREAD

**Issue by mjambon** [returntocorp/sgrep-action#195]
We're getting an error in https://github.com/returntocorp/semgrep/pull/2515/checks?check_run_id=1851883158 indicating that installing the cryptography package requires a Rust compiler.

![image](https://user-images.githubusercontent.com/343265/107178183-78e9f780-6988-11eb-9daa-f3ab88498f5f.png)

Announcement regarding dependency on rust: https://mail.python.org/pipermail/cryptography-dev/2020-December/000998.html
How to install rust: https://www.rust-lang.org/tools/install

**Comment by nbrahms** [comment]
Elevate to `P0` as it's blocking builds.

**Comment by mschwager** [comment]
Assigning to @nbrahms as he opened a PR.
