### ISSUE TITLE
Git failure when running with `--baseline-ref HEAD~1`

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/sgrep-action#198]
Reported in this Slack convo: https://r2c-community.slack.com/archives/CK86BJ5DW/p1612806952179600

**Comment by underyx** [comment]
@nbrahms I don't think this is high priority. The user already solved their issue. We need to decide which of:

- document workaround
- investigate why it worked in the first place before our latest update (is it possible it just *looked* like it was working?)
- add hint in error message
- handle case in semgrep-agent nicely

we should do, but I think it's medium priority at most.

**Comment by nbrahms** [comment]
I actually can't reproduce this:

```
semgrep-agent --baseline-ref head~1 --config p/r2c-ci
| versions          - semgrep 0.38.0 on Python 3.9.1
| environment       - running in environment git, triggering event is 'unknown'
| manage            - not logged in
=== setting up agent configuration
| using semgrep rules from https://semgrep.dev/c/p/r2c-ci
| using default path ignore rules of common test and dependency directories
| reporting findings introduced by these commits:
|   * 5dded71 fix a bad thing
| looking at 1 changed path
| found 1 file in the paths to be scanned
=== looking for current issues in 1 file
```

**Comment by nbrahms** [comment]
Note that this only occurs if `head~1` isn't actually in the git repository.
