### ISSUE TITLE
Missing SSH in semgrep-agent image

### ISSUE THREAD

**Issue by bt-nia** [returntocorp/sgrep-action#206]
Hi!

I'm happily using the `semgrep-agent` image referenced for the [GitlabCI integration](https://semgrep.dev/docs/sample-ci-configs/#gitlab-ci). We have some builds that depend on submodules acquired via `ssh`. Unfortunately, `ssh` does not seem to be installed in the Docker container:
local
```
docker run -v $(pwd):/src --workdir /src returntocorp/semgrep-agent:v1 ssh
Unable to find image 'returntocorp/semgrep-agent:v1' locally
v1: Pulling from returntocorp/semgrep-agent
Digest: sha256:370c6e889ff28f4b5148ad88d6d86d4798d4358d6f1eb5da7114bbe30828e52c
Status: Downloaded newer image for returntocorp/semgrep-agent:v1
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "ssh": executable file not found in $PATH: unknown.
ERRO[0002] error waiting for container: context canceled
```

on a runner:
```
Submodule 'tools/MODULE' (git@gitlab.ORG.com:REPO/REPO.git) registered for path 'tools/REPO'
Cloning into '/builds/ORG/'...
error: cannot run ssh: No such file or directory
fatal: unable to fork
```

Unfortunately I was not able to find the `Dockerfile` for this image to submit a MR , so I hope this is the right place to ask.

**Comment by underyx** [comment]
Hey @bt-nia! This makes sense to me, so I opened a PR. Could you try one scan with `returntocorp/semgrep-agent:pr-207` to confirm if that resolves your issue correctly?

**Comment by underyx** [comment]
```bash
$ docker run -v $(pwd):/src --workdir /src returntocorp/semgrep-agent:pr-207 ssh
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface]
           [-b bind_address] [-c cipher_spec] [-D [bind_address:]port]
           [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]
           [-i identity_file] [-J [user@]host[:port]] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] destination [command]
```

this output seems like your issue should be fixed with #207, but to be safe, it'd be good to know if your submodule setup works right as well with this `ssh` binary 🙃

**Comment by bt-nia** [comment]
That was blazing fast @underyx , thank you!
Unfortunately the issue seems to be something different - I'm getting the same output while using the new image:
```
Running with gitlab-runner 13.8.0 (775dd39d)
  on GKE Docker Runner GSX5ewhL
Resolving secrets
Preparing the "docker" executor
Using Docker executor with image returntocorp/semgrep-agent:pr-207 ...
Pulling docker image returntocorp/semgrep-agent:pr-207 ...
Using docker image sha256:d9f15b89c979fe82bf26ea64ae62be16fca8594170665fedf204bc331b5732f5 for returntocorp/semgrep-agent:pr-207 with digest returntocorp/semgrep-agent@sha256:74c84977ca7bd1983b3b615b70d3404d3d1992766d8d30a3e470fa5434204377 ...
Preparing environment
Running on runner-gsx5ewhl-project-76-concurrent-0 via gitlab-runner-2-8f9b49f49-mrl5s...
Getting source from Git repository
Fetching changes...
Reinitialized existing Git repository in /builds/ORG/PRODUCT/.git/
Checking out 1145930b as refs/merge-requests/9875/head...
Updating/initializing submodules recursively...
Synchronizing submodule url for 'client/unity/Sounds/Fmod'
Synchronizing submodule url for 'tools/NLauncher'
Cloning into '/builds/ORG/PRODUCT/client/unity/Sounds/Fmod'...
error: cannot run ssh: No such file or directory
fatal: unable to fork
```

**Comment by underyx** [comment]
I see, I was worried something like this might happen 😅 

I don't fully understand the bug yet, but in reality, semgrep-agent explicitly skips scanning all submodules, so perhaps you could just skip initializing them by adding this to the job?

```yaml
variables:
  GIT_SUBMODULE_STRATEGY: none
```

See [`GIT_SUBMODULE_STRATEGY` docs](https://docs.gitlab.com/ee/ci/runners/README.html#git-submodule-strategy) and a [prior discussion about semgrep-agent's handling of submodules](https://github.com/returntocorp/semgrep-action/issues/177).

Let me know if this isn't the right solution for you and we can investigate further!

**Comment by underyx** [comment]
You might also want to look at this GitLab issue which seems to be talking about the same problem: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2075

> `pre_clone_script` is executed in our helper image used to clone/fetch sources and restore artifacts and cache. This is an `alpine` based image and it doesn't have `apt-get`. Also, this image is not used for executing user's scripts, so even if you will install ssh there, it would be not available for your build.

> If you need to use ssh, you should move the installation script to `pre_build_script`, and init submodules manually in your build script (`GIT_SUBMODULE_STRATEGY` introduced in v1.10.0 is also realised in the helper image which doesn't have ssh).

**Comment by bt-nia** [comment]
@underyx thank you so much for your help and ideas!
I found it was related to these Gitlab limitations: 
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1113
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/3631
The Gitlab runners do not seem to support `ssh` repos at this time.

I fixed it now by adding:
```
variables:
  GIT_SUBMODULE_STRATEGY: none
before_script:
    - echo "Skipping global before_script."
```
to my semgrep job definition. The variable `GIT_SUBMODULE_STRATEGY` was used to stop resolving of modules and the `before_script` override was necessary because the repo has a global script, which tries to initialize the submodules.

Resulting in:
```
semgrep:analyzer:
  stage: SAST
  image: returntocorp/semgrep-agent:v1
  tags:
    - docker
  allow_failure: true
  variables:
    GIT_SUBMODULE_STRATEGY: none
  before_script:
    - echo "Skipping global before_script."
  script:
    - pushd goof/ # probably remove this in your pipeline
    - python -m semgrep_agent --config "p/r2c-security-audit"
    - popd  # probably remove this in your pipeline
```
Thank you!
