### ISSUE TITLE
Semgrep encountered an unexpected failure

### ISSUE THREAD

**Issue by msorens** [returntocorp/sgrep-action#214]
I run a nightly full (not differential) scan. This error just started appearing two nights ago:
```

docker run -it --rm --init --volume /var/lib/buildkite-agent/builds/core-default-prod-i-063350c612b5a7ca6-4/chef/chef-automate-master-nightly:/go/src/github.com/chef/automate --workdir /go/src/github.com/chef/automate ...LONG LIST OF ENV VARS OMITTED HERE... --label com.buildkite.job-id=49d567d4-e627-4e54-b49c-fd0d01d507e9 returntocorp/semgrep-agent:v1 /bin/sh -e -c $'export SEMGREP_BRANCH=master\nexport SEMGREP_REPO_NAME=chef/automate-nightly\nexport SEMGREP_JOB_URL=https://buildkite.com/chef/chef-automate-master-nightly/builds/729\nexport SEMGREP_REPO_URL=https://github.com/chef/automate\npython -m semgrep_agent --publish-token "$SEMGREP_TOKEN" --publish-deployment $SEMGREP_ID'

Unable to find image 'returntocorp/semgrep-agent:v1' locally
v1: Pulling from returntocorp/semgrep-agent
ba3557a56b15: Pull complete
ffd49e023448: Pull complete
46ec0d464620: Pull complete
44e992cdfdac: Pull complete
7c71687af071: Pull complete
843f7ef86210: Pull complete
904e393ec488: Pull complete
9ea37f7d4fed: Pull complete
394ba8174e4f: Pull complete
e1dd7f2c03b4: Pull complete
Digest: sha256:3cbde1ef2ab0f1faacc1587fa8435b3c32bc65b8ad99db68cfce2be515773655
Status: Downloaded newer image for returntocorp/semgrep-agent:v1
| versions          - semgrep 0.40.0 on Python 3.9.2
Note that no baseline-ref was passed and detected environment is not Github or Gitlab to will default to perfoming a full scan. If you want semgrep to only report on new findings from a pull request please set baseline-ref
| environment       - running in environment git, triggering event is 'unknown'
| manage            - logged in as deployment #48
| policy            - using Chef-nightly
| SEMGREP_BRANCH    - master
| SEMGREP_JOB_URL   - https://buildkite.com/chef/chef-automate-master-nightly/builds/729
| SEMGREP_REPO_NAME - chef/automate-nightly
| SEMGREP_REPO_URL  - https://github.com/chef/automate
=== setting up agent configuration
| using 611 semgrep rules configured on the web UI
| using path ignore rules from .semgrepignore
| found 5510 files in the paths to be scanned
| skipping 961 files based on path ignore rules
=== looking for current issues in 4549 files
 
=== failed command's STDOUT:
 
    {"results": [], "errors": [{"type": "InvalidPatternError", "code": 4, "short_msg": "invalid pattern", "long_msg": "Pattern could not be parsed as a Golang semgrep pattern", "level": "error", "spans": [{"start": {"line": 64, "col": 25}, "end": {"line": 69, "col": 1}, "source_hash": "416e8844e5d5b7c25c46b5aa8096bcb121326774bf8b580592c930b252ee85ac", "file": "/tmp/tmpxdofmn1n.yml", "context_start": null, "context_end": null}]}]}
 
=== failed command's STDERR:
 
    A new version of Semgrep is available. Please see https://github.com/returntocorp/semgrep#upgrading for more information.
    running 611 rules...
 
=== [ERROR] `/root/.local/bin/semgrep --skip-unknown-extensions --disable-nosem --json --no-rewrite-rule-ids --config /tmp/tmpxdofmn1n.yml -o /tmp/tmpozuhr0nw ...LONG LIST OF FILES OMITTED...` failed with exit code 4
 
This is an internal error, please file an issue at https://github.com/returntocorp/semgrep-action/issues/new/choose and include any log output from above.
```

I do not know if the command-line length is of any significance, but that list of files I omitted just above was 21519 characters long.

Does not look like it was a semgrep version bump causing this. As shown, the above error occurred with v0.40.0 and the nights prior to this, which were successful, showed the same version.

Conveniently, semgrep did issue a slack notification (`Semgrep encountered an unexpected failure: https://buildkite.com/chef/chef-automate-master-nightly/builds/728`), which is how I found out about this promptly. 👍 

Oh, and just checked the latest PRs, which run a differential scan, are also failing with the same error.

PRIORITY: URGENT

**Comment by msorens** [comment]
Looks like this started happening Thursday evening. For a moment, I thought I could report that it occurred right about 8:30pm Thursday (because I have a PR right before that passing and a PR right after that failing), but then I noticed that on master there was an earlier run at 6pm that had the same failure. That is peculiar because it did not just start happening at a point in time. The error occurred at 6pm, then did **not** occur at 8:25pm, then occurred again at 8:35 pm and every run thereafter (which was very few runs, just the two nightly runs, in fact).

May or may not be relevant: I have three different invocations of semgrep-agent. All have now exhibited the error:
1. upon pushing to a PR (differential, baseline-ref is `git merge-base master HEAD`
2. upon merging branch to master, then scan on master (differential, baseline-ref is `master~1`)
3. nightly (full, baseline-ref omitted)

**Comment by DrewDennison** [comment]
some non-determinism between runs found locally 
![image](https://user-images.githubusercontent.com/1011067/109570679-7296f900-7ab8-11eb-8c09-5550edf47a87.png)

**Comment by DrewDennison** [comment]
@mschwager @brendongo @aryx @mjambon Brendon and I have a local repro of the rule non-determinism would appreciate help thinking through the potential causes

**Comment by DrewDennison** [comment]
Semgrep seems to always fail on the first run but then after running with `--json` and not exiting early it will work once without the `--json` option and then fail afterwards. I suspect cache invalidation but no hard data on that yet.

**Comment by brendongo** [comment]
I think this is solved
