### ISSUE TITLE
PR diff-aware scans don't scan all commits if main branch is merged into PR branch at some point

### ISSUE THREAD

**Issue by underyx** [returntocorp/sgrep-action#222]
I have a sample PR with this list of commits

<img width="928" alt="Screen Shot 2021-03-11 at 12 36 21" src="https://user-images.githubusercontent.com/1060436/110781591-63f1d400-8266-11eb-9d85-27413b8b54c8.png">

but now the action scans much fewer commits than I'd expect:

```
=== setting up agent configuration
| using 213 semgrep rules configured on the web UI
| using default path ignore rules of common test and dependency directories
| not on head ref 4ce607980a9b27be2c44e943e33f0b9d3f11ccca; checking that out now...
| reporting findings introduced by these commits:
|   * 4ce6079 Update semgrep.yml
|   * cddcd2d Merge branch 'main' into bence/pr-comment-autofix
|   * 4f8fabc Update api.py
|   * fc68f50 Update api.py
| looking at 2 changed paths
| found 2 files in the paths to be scanned
```

which must be because the merge-base was updated when I merged "main into bence/pr-comment-autofix".

**Comment by underyx** [comment]
@nbrahms can you think of a simple fix?

**Comment by nbrahms** [comment]
I wonder if we're calculating the merge base the wrong way round?

**Comment by brendongo** [comment]
I think this was fixed by https://github.com/returntocorp/semgrep-action/pull/456
