### ISSUE TITLE
Error when current ref has .semgrep.yml but baseline does not

### ISSUE THREAD

**Issue by underyx** [returntocorp/sgrep-action#223]
perhaps we should solve this by just continuing on when there’s no config on the baseline ref, and considering there to be 0 pre-existing issues?

See community Slack thread https://r2c-community.slack.com/archives/CK86BJ5DW/p1615392913077600

**Comment by karenlcc** [comment]
Another user also encountered an issue like this.

Quoting the user here in case I misunderstand it. "But current setup default configuration does not work when there is a Pull Request from the fork of the repository (person who is not a collaborator). Github does not allow to use of repository secrets when the job is triggered by a non-collaborator."

**Comment by brendongo** [comment]
Update: got side tracked on other things. Will take a look at this next week

**Comment by brendongo** [comment]
Checking the file exists and treating no file existing as no issues found on the baseline seems like an ok fix

**Comment by underyx** [comment]
> Checking the file exists and treating no file existing as no issues found on the baseline seems like an ok fix

agreed
