### ISSUE TITLE
Specify multiple config rulesets/files in single job

### ISSUE THREAD

**Issue by icio** [returntocorp/sgrep-action#224]
If I run `semgrep --config https://semgrep.dev/p/golang --config https://semgrep.dev/p/gosec` them semgrep will run only 26 rules rather than 37 because the two rulsets share 11 rules.

Trying to replicate that in the workflow YAML, setting `with: config: [...]` yields an error that a sequence is not expected. The workaround we're currently using is to create one workflow job per ruleset that we would like to run, but this means a checkout is run for each, the rules are not de-duplicated, and there's a line for each job taken up in the PR checks at the bottom.

Is there a way to specify multiple `--config` values in one workflow job? If not, please consider this a feature request.

**Comment by dlukeomalley** [comment]
@icio Thanks for filing this ticket! We're in the process of spec'ing out a config file format that specifies rules and their versions for Semgrep to run. I think it will address this specific use case, but we're several weeks out from having that proposal and starting to think about implementation. Are you willing to bear with us as we queue up the config file work or do you need a solution to this sooner?

**Comment by icio** [comment]
I'll make use of what ever option comes first, and I'm not in a huge rush. I've used a few other GitHub actions that let you add command-line arguments to the underlying utility being invoked, which would solve my problem here and might be useful in other ways. But I don't think that's supported though, is it?

Thanks for answering my question :smiley:

**Comment by dlukeomalley** [comment]
@icio - @sabihb added support for multiple config values in `semgrep-agent` here: https://github.com/returntocorp/semgrep-action/pull/289 👏

**Comment by icio** [comment]
Thanks!
