### ISSUE TITLE
Handle Bad Network Connections 

### ISSUE THREAD

**Issue by colleend** [returntocorp/sgrep-action#230]
Two customers have commented that semgrep fails on error 502 and 503 although "fail open" is enabled [here](https://github.com/returntocorp/semgrep-action/issues/228). 

To handle this, we can:
* add retries to network calls
* add different levels of failing (ex: strict mode for errors, which can be set in the cloud, and a network failure option locally)

**Comment by dlukeomalley** [comment]
Tracking work with an internal ticket 🙏
