### ISSUE TITLE
Failed to Download config

### ISSUE THREAD

**Issue by zainab-amir** [returntocorp/sgrep-action#236]
I am facing issue running the semgrep configuration, it has suddenly stopped working:

```shell
=== failed command's STDOUT:

    {"results": [], "errors": [{"type": "SemgrepError", "code": 2, "message": "Failed to download config from https://semgrep.live/dlukeomalley:use-assertEqual-for-equality: bad status code: 404 returned by config url: https://semgrep.live/dlukeomalley:use-assertEqual-for-equality"}, {"type": "SemgrepError", "code": 7, "message": "no valid configuration file found (1 configs were invalid)"}]}


=== failed command's STDERR:

    using config from https://semgrep.live/dlukeomalley:use-assertEqual-for-equality. Visit https://semgrep.dev/registry to see all public rules.
    downloading config...
```

**Comment by chmccreery** [comment]
Hi Zainab - thanks for reporting! I believe this will be fixed by a patch @sabihb has been working on. In the meantime, if you lowercase the url (https://semgrep.live/dlukeomalley:use-assertequal-for-equality) I think that might fix the immediate problem.

**Comment by sabrinabrogren** [comment]
Almost done with the fix for this. It's my top priority today so in case the workaround doesn't work, the fix should be in soon! I'll close this ticket when we've resolved the issue.

**Comment by dlukeomalley** [comment]
@chmccreery @sabihb The lowercased URL does not work for me, getting the same error. Thanks for working on a fix!

**Comment by sabrinabrogren** [comment]
Fix has been applied - let us know if you have any further issues. Thanks!
