### ISSUE TITLE
Ambiguous behavior when both `config` and backend set up

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/sgrep-action#27]
Right now, it's not clear whether the action will use the hard-coded config or use the backend-configured config.

Suggestion is to fail hard with a descriptive error message in this case.

Discovered via dog-fooding on returntocorp/semgrep.

**Comment by underyx** [comment]
There's no easy way to do this, cause one might set up a semgrep-app URL just to get Slack notifications. And even if we check the rules that are configured for the repo, we cannot tell if that YAML was specifically set for the repo, or it's the organization default.

Should we make semgrep-app changes to get this in? I feel like that would be too much effort.

**Comment by brendongo** [comment]
semgrep-agent and semgrep ci will not run a scan (fatal exit) if it is both logged in and an explicit config is set
