### ISSUE TITLE
The returntocorp/semgrep-agent does not include the “--no-rewrite-rule-ids” option

### ISSUE THREAD

**Issue by saltycoder** [returntocorp/sgrep-action#290]
Currently we do not have the option to ignore findings while using the "semgrep-agent" in our CI pipeline.  Given the Rule IDs are being rewritten with a random CI directory name we are unable to add the Rule ID to a “nosemgrep: rule-id” inline comment.

Example renaming of a Rule ID:
```
tmp.tmp.ggDeOk.semgrep-rules.typescript.react.security.audit.react-missing-noopener.react-missing-noopener
```

Error message from semgrep-agent:
```
Error: no such option: --no-rewrite-rule-ids
```

**Comment by dlukeomalley** [comment]
@saltycoder I apologize for our delay responding here. What environment are you running `semgrep-agent` in? What does your invocation of the agent look like? Thanks, we'll dive in once we have some more information on how to reproduce 🙏 

CC @emjin

**Comment by saltycoder** [comment]
@dlukeomalley & @emjin I am using GitLab for the CI and have chosen not to use GitLabs built-in SAST capabilities.  The pipeline runs as a child pipeline for other projects with the Semgrep rulesets being stored within a separate repository.  Here are the steps for the Semgrep stage:

1. On before script, a directory gets created.
2. Git clone of the repository containing the Semgrep rulesets.
3. On script, the Semgrep agent runs.

When viewing the Semgrep results the “check_id” is pre-appended with the temporary directory path where the Semgrep rulesets are being stored for the pipeline.  For example:  “tmp.tmp.ggDeOk.semgrep-rules.”.  This is where the issue is.  Without being able to set the `—no-rewrite-rule-ids` option we are unable to provide other teams with the ability to ignore rulesets for a specific block of code.

Let me know if you need anything else from me.  Thanks!

**Comment by dlukeomalley** [comment]
@saltycoder Thank you for the detail! Are you available early next week to jump on a call to debug or is the project by any chance public for us to poke around? 

When you git clone the repository containing the Semgrep rulesets, is this one of your repos you're cloning or is this `semgrep-agent` downloading rules from the Registry?

I'm in the midst of rewriting our GitLab CI/CD docs now and should good instructions by Monday COB. One of the reason's I'm keen to chat directly is to make sure I'm covering the right content and issues in the docs.

We recently added a GitLab CI/CD config example here (with support for specifying multiple rules and rulesets): https://semgrep.dev/docs/sample-ci-configs/#gitlab-ci
