### ISSUE TITLE
"Rule Recommendation" results included in non-blocking findings count

### ISSUE THREAD

**Issue by underyx** [returntocorp/sgrep-action#320]
When using the "Rule Recommendation" functionality of Semgrep App, the CI runner displays very confusing messages like `2 current issues found` and `2 non-blocking findings hidden`.

**Comment by dlukeomalley** [comment]
Additional feedback from our Community Slack, this behavior continues to be very confusing and frustrating for `semgrep-agent` users:

> User experience feedback: Inventory findings should not be treated as "findings" in tool output, I ran Semgrep via CI on what I expected to be a clean repository and seeing "12 findings" was weird.  They're inventory findings

A second conversation from the same day/time ([here](https://r2c-community.slack.com/archives/CK86BJ5DW/p1627304272068000)):

> New to this, performed a scan on my GitHub repository with semgrep. In the scan results on GitHub I can see there were 28 issues found, however when I switch to the semgrep dashboard it shows no findings. What am I doing wrong ?

**Comment by dlukeomalley** [comment]
Moving this to "bug" again given the level of confusion it has caused.
