### ISSUE TITLE
Make semgrep-agent fail CI only on blocking issues

### ISSUE THREAD

**Issue by underyx** [returntocorp/sgrep-action#34]
semgrep.dev will soon support different actions per rule, so

Assume that `Finding` instances can have a `"dev.semgrep.actions"` key in their `finding.metadata` dict in the `Results` object that semgrep invocations return here: https://github.com/returntocorp/semgrep-action/blob/1e1c2f06307dcdda29c6f8889c2ffb5abb88eb35/src/semgrep_agent/main.py#L120

We should make the agent follow the actions recommended by semgrep-app.

Specifically, we should exit with

```
5 notify-only findings hidden in output
<exit code 0>
``` 

and

```
| [... actual blocking errors here ...]
| [... actual blocking errors here ...]
| [... actual blocking errors here ...]
1 notify-only finding hidden in output
<exit code 1>
``` 

depending on the value of `metadata: dev.semgrep.actions: ["notify", "block"]`

### Downscoping

- We can implement this before the backend supports it. Let's just default findings to have `["block"]` as their actions when not otherwise specified.

**Comment by brendongo** [comment]
Are we hiding the output of a finding if it is set as notify?

**Comment by underyx** [comment]
Yep!
