### ISSUE TITLE
\"semgrep-agent\": executable file not found in $PATH": unknown

### ISSUE THREAD

**Issue by pc10201** [returntocorp/sgrep-action#342]
docker run -v $(pwd):/src --workdir /src returntocorp/semgrep-agent:v1 semgrep-agent --config p/ci --baseline-ref main
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"semgrep-agent\": executable file not found in $PATH": unknown.
ERRO[0000] error waiting for container: context canceled

**Comment by underyx** [comment]
Hey @pc10201! Is it possible that you tried semgrep-agent a long time ago, before we added the command alias? Maybe you just need to run `docker pull returntocorp/semgrep-agent:v1` before running this command. Another user has reported a similar issue where the Docker image came from an outdated Chinese mirror, and needed to be updated.

**Comment by pc10201** [comment]
> Hey @pc10201! Is it possible that you tried semgrep-agent a long time ago, before we added the command alias? Maybe you just need to run `docker pull returntocorp/semgrep-agent:v1` before running this command. Another user has reported a similar issue where the Docker image came from an outdated Chinese mirror, and needed to be updated.

I use returntocorp/semgrep-agent:sha-38dd4bf
It is OK

In chinese returntocorp/semgrep-agent:v1 is old

**Comment by underyx** [comment]
> In chinese returntocorp/semgrep-agent:v1 is old

Thank you for the reply! Do you know if we can do something to make the Chinese mirror update the v1 image?

**Comment by pc10201** [comment]
> > In chinese returntocorp/semgrep-agent:v1 is old
> 
> Thank you for the reply! Do you know if we can do something to make the Chinese mirror update the v1 image?

Maybe you can ask Docker corp to update  chinese CDN node

**Comment by brendongo** [comment]
@pc10201 I sent a support email to dockerhub on ways to remedy this but I think for purposes of this ticket we can have solution as manually trying to pull latest semgrep-agent:v1 image by shahash if other users in china are running into this problem.
