### ISSUE TITLE
Failed to run semgrep with error 2

### ISSUE THREAD

**Issue by mlissner** [returntocorp/sgrep-action#367]
Not sure what you need here, but it said to post logs, so:

```
Error: ROR] `/root/.local/bin/semgrep --skip-unknown-extensions --disable-nosem --json --autofix --dryrun --enable-metrics --no-rewrite-rule-ids --config /tmp/tmpa9ewjgt5.yml --debug -o /tmp/tmpi_79zb8x .github/FUNDING.yml .github/workflows/lint.yml .github/workflows/semgrep.yml .github/workflows/tests.yml .github/workflows/codeql-analysis.yml .github/workflows/pypi.yml .github/dependabot.yml poetry.lock setup.cfg 'Screenshot from 2020-12-17 11-06-09.png' contributor_license_agreement.txt .gitattributes .pre-commit-config.yaml LICENSE pyproject.toml README.md .idea/misc.xml .idea/vcs.xml .idea/pdf-redaction-detector.iml .idea/workspace.xml .idea/modules.xml .idea/inspectionProfiles/profiles_settings.xml .idea/aws.xml .editorconfig SECURITY.md xray/__init__.py` failed with exit code 2
```

Full trace at: https://github.com/freelawproject/pdf-redaction-detector/runs/3560553452?check_suite_focus=true

Thank you!

**Comment by brendongo** [comment]
Looks like it failed because it tried to run a deprecated pattern-where-python rule. Removing the rule should make this pass.

**Comment by mlissner** [comment]
Which rule? I guess I remove it via the dashboard?

**Comment by brendongo** [comment]
It was probably one of 
contrib.dlint.redos.dlint-catastrophic-redos
go.gorrilla.security.audit.handler-attribute-read-from-multiple-sources.handler-attribute-read-from-multiple-sources-dict
python.flask.experimental.correctness.different-route-names.flask-view-func-match-route-params
python.lang.security.audit.insecure-file-permissions.insecure-file-permissions

but I deleted them from the registry so rerunning should work

**Comment by mlissner** [comment]
I tried re-running it, but am still getting errors: https://github.com/freelawproject/pdf-redaction-detector/runs/3560553452?check_suite_focus=true 

(though it says it worked??)

**Comment by mlissner** [comment]
This seems to be working now. Thanks again!
