### ISSUE TITLE
Ease bumping semgrep version

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/sgrep-action#38]
How to change the semgrep version is prone to error for maintenance devs.

Proposal:
- Write a script to bump the version
- Clearly document in the README + link to this in https://returntocorp.quip.com/zrklAwLqfrm7/Using-the-Semgrep-Repo#DfcACAoWAYY

**Comment by underyx** [comment]
We could use this instead of a custom script https://github.com/c4urself/bump2version/

**Comment by underyx** [comment]
Oh, I thought this was for the semgrep repo where stuff like pre-commit hook docs and so on also need to be updated. bump2version is definitely overkill for this repo.

**Comment by brendongo** [comment]
Bumping version is just changing a constant in the Dockerfile now which I think is sufficiently simple.
