### ISSUE TITLE
brew auto-pr is removing ruamel.yaml.clib dependency [PA-659]

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/sgrep-action#418]
**Describe the bug**\
When creating an auto homebrew PR, it removes the ruamle.yaml.clib resource

Looks like this is because ruamel only lists clib as a dependency when running python < 3.10\
[https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree/](https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree/)**init**.py#l16

And in our release script [https://github.com/returntocorp/semgrep/blob/develop/.github/workflows/release.yml#L303](https://github.com/returntocorp/semgrep/blob/develop/.github/workflows/release.yml#L303) we install pipgrip with brew which installs with a 3.10 runtime which means when pipgrip is used to find dependencies of semgrep, it misses clib.

Fix will be to install pipgrip with pip instead so we can run on python < 3.10

From [https://github.com/returntocorp/semgrep/issues/4213](https://github.com/returntocorp/semgrep/issues/4213)\
Originally opened by [brendongo](https://github.com/brendongo)

___

Automatically created from [Linear (#659)]()

*via LinearSync*

**Comment by brendongo** [comment]
Not sure why this is here but anyway this was solved
