### ISSUE TITLE
Semgrep scales linearly with number of languages [PA-660]

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/sgrep-action#419]
From [https://github.com/returntocorp/semgrep-rules/pull/1590:](https://github.com/returntocorp/semgrep-rules/pull/1590:)

> One significant downside of this rule is that the time it takes semgrep to process a large number of files seems to scale linearly with the number of languages listed, not the number of files scanned. Two languages takes about as long as one. Four languages takes twice as long as two, and so on.

This is because we send rules by language to semgrep-core. We should either send language-specific files with each rule or let semgrep-core do file filtering.

From [https://github.com/returntocorp/semgrep/issues/4214](https://github.com/returntocorp/semgrep/issues/4214)\
Originally opened by [emjin](https://github.com/emjin)

___

Automatically created from [Linear (#660)]()

*via LinearSync*

**Comment by brendongo** [comment]
We now send all rules to semgrep-core
