### ISSUE TITLE
Add the ability to configure Semgrep core via the agent

### ISSUE THREAD

**Issue by parsiya** [returntocorp/sgrep-action#42]
Currently, the agent can only accept the config file and prints out the results to stdout (absent other switches). There's no way to get a json output to process the results using the command line.

It would be nice to be able to configure the Semgrep core that is running inside the agent. Mainly, the ability to get the JSON output. I think the easiest way to do so is by accepting Semgrep code switches (e.g., `--json`). This will make the transition between running Semgrep and the agent seamless. The agent is the suggested way of running Semgrep in a CI pipeline so having access to the json output in the container is great.

It seems like this is the location where the context (that contains the config) to Semgrep.

https://github.com/returntocorp/semgrep-action/blob/develop/src/semgrep_agent/main.py#L121

**Comment by dlukeomalley** [comment]
Thanks for filing @parsiya! 

Adding @underyx for input and his thoughts.
