### ISSUE TITLE
Unable to upload "semgrep.sarif" as it is not valid SARIF

### ISSUE THREAD

**Issue by roisec** [returntocorp/sgrep-action#421]
Hi,
I am got this error for the github action:

Run github/codeql-action/upload-sarif@v1
Uploading results
Error details: instance requires property "version"
Error details: instance requires property "runs"
Error: Unable to upload "semgrep.sarif" as it is not valid SARIF:

Have any ideas?

**Comment by ievans** [comment]
Hi @RoiSec, can you share the SARIF file?

**Comment by ievans** [comment]
Probably a dupe of https://github.com/returntocorp/semgrep-action/issues/378

**Comment by roisec** [comment]
https://github.com/RoiSec/caspion/runs/4141290747

**Comment by brendongo** [comment]
@RoiSec doesnt look like the sarif file is there?

**Comment by brendongo** [comment]
I think closed by #457
