### ISSUE TITLE
Incompatible with act

### ISSUE THREAD

**Issue by jayvdb** [returntocorp/sgrep-action#428]
I am using the ["medium" runner](https://github.com/nektos/act#runners) of https://github.com/nektos/act , a local github actions runner, which fails with `sh.CommandNotFound: semgrep`

```
% act
[Semgrep/Scan] 🚀  Start image=catthehacker/ubuntu:act-latest
[Semgrep/Scan]   🐳  docker run image=catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Semgrep/Scan]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root
[Semgrep/Scan]   🐳  docker cp src=/path/to/<repo>/. dst=/path/to/repo
[Semgrep/Scan]   🐳  docker exec cmd=[mkdir -p /path/to/repo] user=
[Semgrep/Scan] ⭐  Run actions/checkout@v2
[Semgrep/Scan]   ✅  Success - actions/checkout@v2
[Semgrep/Scan] ⭐  Run returntocorp/semgrep-action@v1
INFO[0001]   ☁  git clone 'https://github.com/returntocorp/semgrep-action' # ref=v1
[Semgrep/Scan]   🐳  docker run image=returntocorp/semgrep-agent:v1 platform= entrypoint=[] cmd=[]
| Traceback (most recent call last):
|   File "/usr/local/bin/semgrep-agent", line 2, in <module>
|     from semgrep_agent.__main__ import error_guard
|   File "/app/src/semgrep_agent/__main__.py", line 6, in <module>
|     from semgrep_agent.main import main
|   File "/app/src/semgrep_agent/main.py", line 18, in <module>
|     from semgrep_agent import semgrep
|   File "/app/src/semgrep_agent/semgrep.py", line 42, in <module>
|     semgrep_exec = sh.semgrep.bake(_ok_code={0, 1}, _tty_out=False, _env=ua_environ)
|   File "/usr/local/lib/python3.9/site-packages/sh.py", line 3672, in __getattr__
|     return self.__env[name]
|   File "/usr/local/lib/python3.9/site-packages/sh.py", line 3457, in __getitem__
|     raise CommandNotFound(k)
| sh.CommandNotFound: semgrep
[Semgrep/Scan]   ❌  Failure - returntocorp/semgrep-action@v1
Error: exit with `FAILURE`: 1
```

**Comment by brendongo** [comment]
It looks like `act` might not be looking for `semgrep` in the right path? We definitely install semgrep https://github.com/returntocorp/semgrep-action/blob/develop/Dockerfile#L13 in the docker image so this might be something to file with act?

**Comment by jayvdb** [comment]
The Dockerfile is setting `PATH=/root/.local/bin:${PATH}`, and that works when running the image locally.

But when I look at the env under `act` I see
```
'HOME': '/root'
...
'INSTALLED_SEMGREP_VERSION': '0.73.0',
...
'PATH': '/opt/hostedtoolcache/node/14.18.1/x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'

'R2C_USE_REMOTE_DOCKER': '1',
...
'SEMGREP_ACTION': 'true',
'SEMGREP_ACTION_VERSION': 'v1',
...
'USER': 'root'
```

https://github.com/nektos/act/issues/827 seems similar, and suggests it might be fixed on `master`.  Will give that a go.

**Comment by MtMafia** [comment]
what's going on?

**Comment by jayvdb** [comment]
When I use act `master` on macos, the PATH still doesnt have `/root/.local/bin` in it.

**Comment by catthehacker** [comment]
The PR you linked fixed sourcing environment variables from Docker images but only for when `act` uses them as a base container (` -P, --platform stringArray             custom image to use per platform (e.g. -P ubuntu-18.04=nektos/act-environments-ubuntu:18.04)`)

This doesn't work for your use case because `act` doesn't inspect the image it builds (yet) whether it be an action using Docker or step using `docker://`

**Comment by ronwaisberg-okta** [comment]
I've had success running semgrep-agent in act by overwriting the CMD instruction and specifying PATH like so:
```
with:
  args: "sh -c \"PATH=/root/.local/bin:${PATH} semgrep-agent\""
```
docs: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepswithargs

**Comment by brendongo** [comment]
Closing as this seems like an act issue?
