### ISSUE TITLE
Dangling .semgrep_logs

### ISSUE THREAD

**Issue by michal-klimek** [returntocorp/sgrep-action#441]
The PR https://github.com/returntocorp/semgrep-action/pull/434 made our github actions pipelines unusable, because on self hosted runner the action leaves files in the `.semgrep_logs` directory. The directory is owned by a root, so subsequent checkout actions fail

**Comment by brendongo** [comment]
Hmm we put it there so it is easy for people running the docker container locally or in CI to access the debugging logs. Can you add a step after semgrep to remove that directory?

**Comment by michal-klimek** [comment]
Yes, I deal with it using an extra step. Anyway it was not obvious that these files could not be deleted when the workflow is run once again. Without inspecting action's source code one could not know that the action would write files owned by a root, moreover our workflows stopped working suddenly without a visible cause.

**Comment by brendongo** [comment]
Hmm yes our bad 😅 there's probably a fix with the user we use in docker but we're in the process of porting over most of semgrep-agent functionality into semgrep itself so probably not worth the effort to dig through right now :D

**Comment by emjin** [comment]
+1 from Clara. Maybe after we port this we can change the default behavior to remove the logs folder on a successful local run?

**Comment by brendongo** [comment]
Closed by https://github.com/returntocorp/semgrep-action/pull/496
