### ISSUE TITLE
move semgrep-action functionality into semgrep

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep-action#451]
This is a pinned issue to advertise the work that @brendongo is leading to move all/most semgrep-action functionality into semgrep itself. Would love to invite comments from the community!

**Comment by Sjord** [comment]
[feat(baseline): Enable semgrep to perform baseline scans by brendongo · Pull Request #4571 · returntocorp/semgrep](https://github.com/returntocorp/semgrep/pull/4571)

**Comment by Sjord** [comment]
Experimental baseline scanning is present in [semgrep 0.82](https://github.com/returntocorp/semgrep/releases/tag/v0.82.0).  Run with --baseline-commit GIT_COMMIT to only
show findings that currently exist but did not exist in GIT_COMMIT.

**Comment by brendongo** [comment]
This is fully in semgrep as `semgrep ci`
