### ISSUE TITLE
Facing this error while running semgrep

### ISSUE THREAD

**Issue by ShiftLefter** [returntocorp/sgrep-action#458]
Hi, 

Any ideas why I'm facing this error?

```Error: ROR] `/root/.local/bin/semgrep --skip-unknown-extensions --disable-nosem --json --autofix --dryrun --time --timeout-threshold 3 --config https://semgrep.dev/c/p/security-audit ... --debug -o .semgrep_logs/semgrep_agent_output .github/workflows/semgrep.yaml .semgrepignore` failed with exit code 7```

**Comment by ievans** [comment]
Can you share the output of `.semgrep_logs/semgrep_agent_output`? What version of semgrep are you running? 

docs on exit code 7: https://semgrep.dev/docs/cli-usage/#:~:text=7%20%3A%20All%20rules%20in%20config,does%20not%20understand%20specified%20language

**Comment by ShiftLefter** [comment]
@ievans its resolved, made a typo in rule name
