### ISSUE TITLE
semgrep_agent_output for HEAD scan overwritten by baseline scan

### ISSUE THREAD

**Issue by ronwaisberg-okta** [returntocorp/sgrep-action#471]
Hi there, my use-case relies on me accessing metavariable information contained in `semgrep_agent_output` however in CI diffing mode I experience the following issue:

1. `semgrep_agent_output` is first written in `_get_head_findings()` through `invoke_semgrep()`
2. if the baseline commit needs to be scanned, `semgrep_agent_output` will be overwritten in `_update_baseline_findings()`
3. the less useful version of `semgrep_agent_output` is left on disk with findings from the baseline instead of HEAD.

I need the findings (and corresponding metavar info) from the HEAD scan instead of the baseline. The easiest approach, which I discussed with @emjin is to write the baseline scan output to a separate file, implemented in PR #472

**Comment by brendongo** [comment]
Hi can you explain your use case a little more? The semgrep_agent_output file is intended to be for debug logging and not intended to be stable output. Does the --json flag not give you something usable?
