### ISSUE TITLE
Errors when moving files around and using symbolic links

### ISSUE THREAD

**Issue by aryx** [returntocorp/sgrep-action#481]
See the error in semgrepdep here:
https://github.com/returntocorp/semgrep/runs/4766737510?check_suite_focus=true
The error happens with semgrepdep, not semgrep-action, but semgrepdep reuses code
from semgrep-action so the bug is probably there!

**Comment by brendongo** [comment]
Looks like our git logic didn't handle the rename well ```p-core/src/core/Semgrep_core_response.atd → interfaces/Output_from_core.atd ``` 

```
FileNotFoundError: [Errno 2] No such file or directory: '/github/workspace/interfaces/Output_from_core.atd'
```

**Comment by ievans** [comment]
No way to reproduce this, given how old the code copied into Semgrepdep was. Lack of corroboration means it's highly likely it was fixed in action meanwhile.
