### ISSUE TITLE
none unique id for different vulnerabilities

### ISSUE THREAD

**Issue by zakrush** [returntocorp/sgrep-action#488]
Hi. I'm testing semgrep-agent with different scenarios. So. For test I was scanning only one file: 

[ImportDirectoryController.txt](https://github.com/returntocorp/semgrep-action/files/7888235/ImportDirectoryController.txt)
(rename it to js instead txt)

I run it this command:
```
docker run -v $(pwd):/src --workdir /src returntocorp/semgrep-agent:v1 semgrep-agent --config "r/ajinabraham.njsscan.sql_injection.node_sqli_injection" --gitlab-json > reports/GL-master.json
```
Here is 2 vulnerabilities. They have the same unique id. 
How are you calculated this id? 
The same ID for different vulnerability I think it's incorrect. In my case I can't to do correct upload report to DefectDojo. Also I will have plans of using id for deduplications. 

Report here:
[GL-new_sql.txt](https://github.com/returntocorp/semgrep-action/files/7888250/GL-new_sql.txt)

**Comment by brendongo** [comment]
I think https://github.com/returntocorp/semgrep-action/blame/develop/src/semgrep_agent/findings.py#L139 will need to be changed to https://github.com/returntocorp/semgrep-action/blame/develop/src/semgrep_agent/findings.py#L173 but not too sure what downstream effects of this change will be

**Comment by zakrush** [comment]
@brendongo  yes. I agree. 
```str(uuid.uuid5(uuid.NAMESPACE_URL, str(self.path))),```
It's not unique hash data. If semgrep will find different findings to same file, it's was have the same id, it's wrong.

**Comment by zakrush** [comment]
So. I tested this solution and It's work fine for me.

**Comment by zakrush** [comment]
@brendongo do you know where is it logic now? I wanted to do pull request, but see that findings.py was deleted

**Comment by zakrush** [comment]
create pull request for v1 
https://github.com/returntocorp/semgrep-action/pull/556

**Comment by brendongo** [comment]
Sorry just seeing this now https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/formatter/gitlab_sast.py#L41 is where it is located now
