### ISSUE TITLE
SAST Integration with GitLab will stop working in GitLab 15.0 (2022-05-22)

### ISSUE THREAD

**Issue by theoretick** [returntocorp/sgrep-action#489]
Hey folks! Just wanted to give you a heads-up on an upcoming deprecation from GitLab.

[GitLab SAST schemas below 14.0.0](https://docs.gitlab.com/ee/update/deprecations#sast-schemas-below-1400) have been deprecated.

[src/semgrep_agent/main.py#L386](https://github.com/returntocorp/semgrep-action/blob/3a2579faa7ee08d0703f2472f6699d5218e9b346/src/semgrep_agent/main.py#L386) is using a deprecated version:

>    "version": "2.0",

[The latest version of the schema is 14.1.0](https://gitlab.com/gitlab-org/gitlab/-/tree/master/ee/lib/ee/gitlab/ci/parsers/security/validators/schemas/14.1.0). There are [other schemas available](https://gitlab.com/gitlab-org/gitlab/-/tree/master/ee/lib/ee/gitlab/ci/parsers/security/validators/schemas); any version from 14.0.0 is supported.

From GitLab 15.0 (2022-05-22), any reports submitted using an unsupported version will be rejected.

**Comment by theoretick** [comment]
Worth noting that [the recent addition of support for GL secret scanning reports](https://github.com/returntocorp/semgrep-action/pull/403/files) [is already at 14.0.0](https://github.com/returntocorp/semgrep-action/blob/3a2579faa7ee08d0703f2472f6699d5218e9b346/src/semgrep_agent/main.py#L394) so looks like no change should be needed there

**Comment by brendongo** [comment]
This was fixed in semgrep 0.98.0 with https://github.com/returntocorp/semgrep/pull/5532
