### ISSUE TITLE
git internal error

### ISSUE THREAD

**Issue by erfanmoshiri** [returntocorp/sgrep-action#500]
`/root/.local/bin/semgrep --skip-unknown-extensions --disable-nosem --json --config https://semgrep.dev/c/p/security-audit --config https://semgrep.dev/c/p/secrets --config https://semgrep.dev/c/p/django --config https://semgrep.dev/c/p/docker --config https://semgrep.dev/c/p/auto --config https://semgrep.dev/c/p/gitlab-bandit --metrics off --debug -o /tmp/tmpkm0uunj0 campaign/models/created_content.py campaign/models/reject_reason.py` failed with exit code 7

url = 'https://git.yektanet.com/jaryan/back-end/-/jobs/246062'

**Comment by brendongo** [comment]
Hi @erfanmoshiri are you able to paste more of the logs here?
