### ISSUE TITLE
internal error when running GitHub action on Nomad repo

### ISSUE THREAD

**Issue by jrasell** [returntocorp/sgrep-action#503]
Firstly thank you; the Nomad team recently integrated semgrep into our CI process which has proved immediately useful. We are, however, getting an internal error reported when running via GitHub actions. Any help would be greatly appreciated.

Link: https://github.com/hashicorp/nomad/runs/4963163639?check_suite_focus=true

Output:

```
using semgrep rules from the committed .semgrep/ directory
| not on head ref 28fb4b5133f5086b5e53d93d8b1b935da83d6340; checking that out now...
| reporting findings introduced by these commits:
|   * 28fb4b5 core: prevent malformed plans from crashing leader
| looking at 3 changed paths
=== looking for current issues in 3 files
| returning to original head revision a32036e3318313effeaf123e49f9af29401673fb

=== failed command's STDOUT:



=== failed command's STDERR:



Error: ROR] `/root/.local/bin/semgrep --skip-unknown-extensions --disable-nosem --json --autofix --dryrun --time --timeout-threshold 3 --config .semgrep/ --debug -o /tmp/tmp_iev1gfz nomad/plan_endpoint.go nomad/plan_endpoint_test.go nomad/structs/structs.go` failed with exit code 7

This is an internal error, please file an issue at https://github.com/returntocorp/semgrep-action/issues/new/choose
and include any log output from above.

```

**Comment by ievans** [comment]
Hey, thanks for the great error report! I suspect that your rules are invalid -- [see CLI reference for exit code 7 (invalid config)](https://semgrep.dev/docs/cli-usage/#:~:text=7%3A%20At%20least%20one%20rule%20in%20config%20is%20invalid )

Can you try running `semgrep --config .semgrep/ nomad/` locally, without the --quiet flag?

**Comment by brendongo** [comment]
If I am understanding github UI correctly looks like https://github.com/hashicorp/nomad/tree/b-validate-plan is the branch this internal error is reporting on and it looks like it doesn't have a .semgrep directory in it so that might be why this is failing as invalid rule config

**Comment by jrasell** [comment]
Hi @ievans and @brendongo and thanks for the quick responses. I took a deeper look last night and it does seem semgrep attempted to run its action against and branch that didn't have the rules directory available. Apologies for the noise and i'll close this issue out.

**Comment by ievans** [comment]
@jrasell no need to apologize, you just opened a ticket exactly as the error message asked you to! I filed a new ticket specifically about the confusing output message: https://github.com/returntocorp/semgrep-action/issues/504
