### ISSUE TITLE
"internal error" reported if rules directory is missing

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep-action#504]
If you run semgrep from a branch that doesn't have rules, it will report an internal error:

```
Error: ROR] `/root/.local/bin/semgrep --skip-unknown-extensions --disable-nosem --json --autofix --dryrun --time --timeout-threshold 3 --config .semgrep/ --debug -o /tmp/tmp_iev1gfz nomad/plan_endpoint.go nomad/plan_endpoint_test.go nomad/structs/structs.go` failed with exit code 7

This is an internal error, please file an issue at https://github.com/returntocorp/semgrep-action/issues/new/choose
and include any log output from above.
```

Expected behavior would be an error message telling you `invalid config, path .semgrep/ not found`. 

Originally reported in https://github.com/returntocorp/semgrep-action/issues/503

**Comment by brendongo** [comment]
Now that we only call semgrep once and it pulls the rules we always use latest rules on both head and base
