### ISSUE TITLE
Semgrep Agent Error 

### ISSUE THREAD

**Issue by utkarsh08kher** [returntocorp/sgrep-action#515]
Hi Team,

We are getting the below error while running the Semgrep github actions agent

**Log Line**
```

Run returntocorp/semgrep-action@v1
check_suite_focus=true#step:4:8)1.0 on Python 3.[9].[10]
| environment       - running in environment github-actions, triggering event is 'push'
| manage            - authenticated as the organization 'XXXXX'
| policy            - using Rule Board - Block column, Rule Board - Audit column
=== setting up agent configuration
| using [13] semgrep rules configured on the web UI
| using 0 code asset inventory rules
=== looking for current issues in 1 file

=== failed command's STDOUT:



=== failed command's STDERR:



Error: ROR] `/root/.local/bin/semgrep --skip-unknown-extensions --disable-nosem --json --autofix --dryrun --time --timeout-threshold 3 --config .semgrep_logs/semgrep_app_rules.yaml --enable-metrics --no-rewrite-rule-ids --debug -o /tmp/tmphviwx9a2 .` failed with exit code 2

This is an internal error, please file an issue at https://github.com/returntocorp/semgrep-action/issues/new/choose
and include any log output from above.
```

Can you guys please take a look and let me know, thanks!

**Comment by nbrahms** [comment]
Hi @utkarsh08kher ,

I'm sorry you ran into this! Thank you for the bug report, and helping us improve semgrep-action.

Are you able to set:
```yaml
env:
  SEMGREP_AGENT_DEBUG: 1
```
in your workflow config file, in the `uses: returntocorp/semgrep-action@v1` block?

You may also want to enable step debugging in GHA according to https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging.

If any of these logs are sensitive, please reach out to me on the r2c community Slack!
