### ISSUE TITLE
Commit hash is not provided in the output of a diff-aware scan

### ISSUE THREAD

**Issue by utkusen** [returntocorp/sgrep-action#530]
Hi,

I'm running a diff aware scan and receiving the output in json format:

`docker pull returntocorp/semgrep-agent:v1 && docker run -v $(pwd):$(pwd) --workdir $(pwd) returntocorp/semgrep-agent:v1 semgrep-agent --config auto --baseline-ref main --json`

The pull request that I'm scanning has 3 commits in it and semgrep shows that information as well:

```
| using semgrep rules from auto
| reporting findings introduced by these commits:
|   * 788bca4 uc
|   * cfd7a50 iki
|   * 41b83ca bir
```

Semgrep finds one issue, but the output doesn't contain the commit hash value

```
[{"check_id": "go.lang.security.audit.net.use-tls.use-tls", "path": "util/http.go", "line": 20, "column": 2, "message": "Found an HTTP server without TLS. Use 'http.ListenAndServeTLS' instead. See https://golang.org/pkg/net/http/#ListenAndServeTLS for more information.", "severity": 1, "syntactic_context": "http.ListenAndServe(\":8080\",nil)", "index": 0, "fixed_lines": ["\thttp.ListenAndServeTLS(\":8080\", certFile, keyFile, nil)"], "end_line": 20, "end_column": 34, "commit_date": "2022-03-04T11:06:22+01:00", "metadata": {"category": "security", "confidence": "MEDIUM", "cwe": "CWE-319: Cleartext Transmission of Sensitive Information", "license": "Commons Clause License Condition v1.0[LGPL-2.1-only]", "owasp": "A3: Sensitive Data Exposure", "references": ["https://golang.org/pkg/net/http/#ListenAndServeTLS"], "technology": ["go"]}, "syntactic_id": "d132660ad07ab9c9abbd114463c0ea0d", "is_blocking": true}]
```

Therefore, I don't know which commit has the vulnerable code. I need the commit's hash value in order to interact with Github's API. This is a required value. I wonder why the output doesn't contain this information or is there a way to access it?

**Comment by caglarsayin** [comment]
Heey
+1

**Comment by brendongo** [comment]
@utkusen we currently don't plan on including the specific commit an issue was first introduced in. With PR scans we only ever scan the head commit and the base commit so all semgrep would know is that it existed in head but not base. semgrep-app (semgrep.dev) makes PR comments using the head commit to interact with github apis
