### ISSUE TITLE
Passing options into the action

### ISSUE THREAD

**Issue by garyowner06** [returntocorp/sgrep-action#534]
Hi,

Currently trying to reduce the noise of the alerts and focus on high findings, but I'm struggling to find out how to replicate the cli options in the GitHub Actions playbook.

**Comment by ievans** [comment]
hi @garyowner06 , thanks for letting us know, and sorry for the frustration

we are currently migrating most action functionality into Semgrep itself: https://github.com/returntocorp/semgrep-action/issues/451 which will hopefully resolve the option discrepancy soon

**Comment by garyowner06** [comment]
thanks @ievans for the update, will keep an eye out for that issue implementation.

**Comment by brendongo** [comment]
@garyowner06 see `semgrep ci --help` with latest semgrep >= 0.86.5
