### ISSUE TITLE
Internal error on gradle.properties

### ISSUE THREAD

**Issue by jonandersenverkada** [returntocorp/sgrep-action#540]
Error when using GitHub action to analyze a pull request.  There is nothing special about the GitHub action configuration.

The internal error:
Run returntocorp/semgrep-action@v1
/usr/bin/docker run --name returntocorpsemgrepagentv1_413d70 --label 29a9[5](https://github.com/verkada/Verkada-Android/runs/5577096832#step:4:5)e --workdir /github/workspace --rm -e INPUT_PUBLISHTOKEN -e INPUT_AUDITON -e INPUT_CONFIG -e INPUT_GENERATESARIF -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Verkada-Android/Verkada-Android":"/github/workspace" returntocorp/semgrep-agent:v1
| versions          - semgrep 0.81.0 on Python 3.9.10
| environment       - running in environment github-actions, triggering event is 'pull_request'
| manage            - authenticated as the organization 'verkada'
| policy            - using Starter Policy, Verkada Policy, Security Policy
=== setting up agent configuration
| using 84[6](https://github.com/verkada/Verkada-Android/runs/5577096832#step:4:6) semgrep rules configured on the web UI
| using 542 code asset inventory rules
| not on head ref ed3a132e3606634bab42413812e[7](https://github.com/verkada/Verkada-Android/runs/5577096832#step:4:7)403f06f50c69; checking that out now...
| reporting findings introduced by these commits:
|   * ed3a132 Increment version 3.16.0 (120)
| looking at 1 changed path
=== looking for current issues in 1 file
| returning to original head revision 30[8](https://github.com/verkada/Verkada-Android/runs/5577096832#step:4:8)43d005a5deb22adc0aab000[9](https://github.com/verkada/Verkada-Android/runs/5577096832#step:4:9)46c2d4[23](https://github.com/verkada/Verkada-Android/runs/5577096832#step:4:23)45af3

=== failed command's STDOUT:

=== failed command's STDERR:

Error: ROR] `/root/.local/bin/semgrep --skip-unknown-extensions --disable-nosem --json --autofix --dryrun --time --timeout-threshold 3 --config .semgrep_logs/semgrep_app_rules.yaml --enable-metrics --no-rewrite-rule-ids --debug -o /tmp/tmp1j4fn8_h gradle.properties` failed with exit code 7

This is an internal error, please file an issue at https://github.com/returntocorp/semgrep-action/issues/new/choose
and include any log output from above.

**Comment by dlukeomalley** [comment]
Hi @jonandersenverkada, we had an brief outage today that caused scan failures for people running the [p/secrets](https://semgrep.dev/p/secrets) ruleset. The outage began on 3/16/22 at 2:03 PM PDT and was resolved at 2:33 PM PDT (lasting 30 minutes). Is this now succeeding for you?

CC @faceyacc @Jason-Lim00 @holdenmcg
