### ISSUE TITLE
Semgrep Action failed with exit code 2 when no issues are found

### ISSUE THREAD

**Issue by pauloiza10** [returntocorp/sgrep-action#548]
We are getting the same error across multiple repos today when yesterday we didn't see any of these errors.

If semgrep finds an issue, the SARIF report is generated. For some reason, it only fails with exit code 2 if it finds no issues.

Have tried disabling the timeout `.github/workflows/semgrep.yaml`
```
       ...
        env:
          SEMGREP_TIMEOUT: 0
       ...
```

But that did not resolve the issue nor change the time it took for the action to execute. 

Could someone please take a look and help identify the underlying issue?

```
| versions          - semgrep 0.81.0 on Python 3.9.10
| looking at 3 changed paths
=== looking for current issues in 3 files
| No current issues found
...
=== not looking at pre-existing issues since there are no current issues
=== re-running scan to generate a SARIF report

=== failed command's STDOUT:



=== failed command's STDERR:



Error: ROR] `/root/.local/bin/semgrep --config https://semgrep.dev/c/p/ci --config https://semgrep.dev/c/p/r2c --config https://semgrep.dev/c/p/auto --config https://semgrep.dev/c/p/golang --config https://semgrep.dev/c/p/secrets --config https://semgrep.dev/c/p/r2c-ci --config https://semgrep.dev/c/p/r2c-bug-scan --config https://semgrep.dev/c/p/owasp-top-ten --config https://semgrep.dev/c/p/r2c-security-audit --config https://semgrep.dev/c/p/sql-injection --config https://semgrep.dev/c/p/command-injection --config https://semgrep.dev/c/p/security-audit --config https://semgrep.dev/c/p/insecure-transport --config https://semgrep.dev/c/r/contrib.dlint --debug --sarif -o /tmp/tmpzn68x6z_ docker-compose-debug.yml bin/dev-server env.example` failed with exit code 2

This is an internal error, please file an issue at https://github.com/returntocorp/semgrep-action/issues/new/choose
and include any log output from above.
```

**Comment by brumhard** [comment]
Same happens on version `semgrep 0.83.0 on Python 3.9.11`. Could maybe be an issue the SARIF report generation. It also feels a bit flaky since sometimes it still seems to work 👀

**Comment by brumhard** [comment]
I think removing `generateSarif: "1"` resolves the issue for now, so I guess there's some issue with that.

**Comment by brendongo** [comment]
@brumhard can you give an example reproduction with file + rule so we can investigate

**Comment by brumhard** [comment]
Hi @brendongo that's kinda tricky, since it seems to be a bit flaky. Removing `generateSarif: "1"` did seem to improve the pipelines a bit but even then some pipelines failed without any error message. I'll try to update if I find any pattern.

**Comment by brendongo** [comment]
We stabilized the sarif generation with 0.86.5 (or latest semgrep-action) let us know if you are still seeing failures @brumhard @pauloiza10

**Comment by brumhard** [comment]
@brendongo I did 3 runs now and they all were successful so I guess for me the issue is resolved. Thank you 👍🏻

**Comment by brendongo** [comment]
Thanks @brumhard!
