### ISSUE TITLE
UnknownLanguageError - This is an internal error, please file an issue

### ISSUE THREAD

**Issue by kodbe** [returntocorp/sgrep-action#553]
I am running this command in my GitLab CI job:
semgrep-agent --gitlab-json
I am getting this error:
`{"errors": [{"code": 8, "level": "error", "long_msg": "unsupported language: dockerfile. supported languages are..`

`
=== failed command's STDERR:
=== [ERROR] `/root/.local/bin/semgrep --skip-unknown-extensions --disable-nosem --json --autofix --dryrun --enable-metrics --no-rewrite-rule-ids --config /tmp/tmpjjtdox8p.yml --debug -o /tmp/tmpir37l7pa .gitlab-ci.yml` failed with exit code 8
`

**Comment by brendongo** [comment]
Seems like you are using a version of semgrep that does not include dockerfile support. Can you post more logs / the version of semgrep this is running? We added dockerfile support on https://github.com/returntocorp/semgrep/blob/develop/CHANGELOG.md#0790---2022-01-20
