### ISSUE TITLE
Diff-aware doesn't report new findings if the new finding has the same (rule_id, path, line_of_code) as the one before

### ISSUE THREAD

**Issue by underyx** [returntocorp/sgrep-action#56]
Assume you have this diff:

```diff
  eval(foo)
  # some code
+ eval(foo)
```

The addition of a new eval security issue should be warned about on a PR. Right now we use a `set` to figure out what findings are new, which would make the agent unaware about the new issue. If we used a `Counter`, we could warn that there are more instances of the same thing now.

**Comment by Isaac0616** [comment]
Thinking it a bit more.
I think there are cases that even the `Counter` is not ideal.
For example:
```diff
- @web(skip_csrf_check=True)
def safe_endpoint(...):

+ @web(skip_csrf_check=True)
def sensitive_endpoint(...):
```
is bad but won't be flagged.
To solve it, I guess we have to check the actual changed lines between commits?

**Comment by nbrahms** [comment]
I think we'd likely solve the 90% case by just incorporating the finding index on the file into the syntactic context.

Certainly to your point @Isaac0616 , we'd like to catch your case in the future, but we also want to avoid falsely flagging on simple refactors that touch unrelated code.

One idea we've bandied about in the past is to treat the previous and next lines as part of the syntactic context, although there are still possible false negatives in this case.

Another option would just be to make whether or not to include the line number as part of the syntactic context a configurable option, so you could choose your own noise.
