### ISSUE TITLE
Python pip dependency conflict with semgrep version  0.86.0 and  0.87.0

### ISSUE THREAD

**Issue by caglarsayin** [returntocorp/sgrep-action#562]
Semgrep-agent is always conflicting with glom package on pypi. 
The version we tried are the ones on pypi
0.1.0b2
0.1.0b1
0.1.0b0
The conflict is caused by:
	semgrep 0.86.0 depends on glom~=22.1
	semgrep-agent 0.1.0b2 depends on glom<21.0.0 and >=20.8.0

**Comment by brendongo** [comment]
Hi @caglarsayin starting 0.86.0 all the functionality in semgrep-agent is mirrored in `semgrep ci` If you follow up with how you are using semgrep-agent right now I can help you craft the equivalent invocation for `semgrep ci`

**Comment by caglarsayin** [comment]
ahh, I see okay.
We need a case for pull requests. I think the new option is `--baseline-commit` instead of `--baseline-ref` but I guess they do not work exactly in the same way. `baseline-ref` one checks all the commits between two refs though `baseline-commit` only checks 1 commit. Is there a solution for this?

**Comment by brendongo** [comment]
@caglarsayin both flags work exactly the same way so you should be able to just swap out the flags.

Both flags mean semgrep will only show findings that exist in head but do not exist in the given ref/commit

**Comment by brendongo** [comment]
@caglarsayin did this work for you?

**Comment by brendongo** [comment]
Closing as we don't expect semgrep-agent on pypi to be widely used and all functionality is exposed in semgrep > 0.86.0

**Comment by caglarsayin** [comment]
Thank you
