### ISSUE TITLE
Passing verbose flag to semgrep-action

### ISSUE THREAD

**Issue by raoganeshr** [returntocorp/sgrep-action#563]
Is it possible to also add a flag to pass --verbose to semgrep? Currently I cant find an option to do so.

**Comment by brendongo** [comment]
Hey @raoganeshr. Would you be able to switch usage from `semgrep-agent` to `semgrep ci`? The later has all the functionality of `semgrep-agent` and supports the `--verbose` flag

**Comment by raoganeshr** [comment]
Hi @brendongo do you mean to use semgrep container with ci command?

**Comment by brendongo** [comment]
Yep! See https://semgrep.dev/docs/semgrep-ci/sample-ci-configs/#github-actions most important in the config are that we changed from `returntocorp/semgrep-action` to `returntocorp/semgrep` and instead of running `semgrep-agent` we run `semgrep ci` subcommand
