### ISSUE TITLE
Semgrep-action no longer works with multiple configs

### ISSUE THREAD

**Issue by Sjord** [returntocorp/sgrep-action#565]
When I pass multiple `--config` flags to semgrep-agent, it used to use all the rules, but now it only uses the last ruleset given. When I pass `--config "r/php" --config "r/javascript"`, I expect it to run both PHP and JavaScript rules, but it only uses JavaScript rules.

```
$ docker run -v "$PWD:/mysrc" -w "/src" returntocorp/semgrep-agent:v1 semgrep-agent --config "r/php" --config "r/javascript"
=== Running: SEMGREP_RULES=r/javascript semgrep ci
Running `semgrep ci` without API token but with configs ('r/javascript',)
...
```

Previously, it would show something like this:

```
| versions          - semgrep 0.81.0 on Python 3.9.10
| environment       - running in environment git, triggering event is 'unknown'
| manage            - not logged in
=== setting up agent configuration
| using semgrep rules from https://semgrep.dev/c/r/php
| using semgrep rules from https://semgrep.dev/c/r/javascript
...
```

**Comment by brendongo** [comment]
@Sjord are you able to transition to using `semgrep` instead?

```docker run -v "$PWD:/mysrc" -w "/src" returntocorp/semgrep semgrep ci --config "r/php" --config "r/javascript"``` should do the same thing as your above invocation
