### ISSUE TITLE
SARIF Error: instance additionalProperty "fixes" exists in instance when not allowed

### ISSUE THREAD

**Issue by HariSekhon** [returntocorp/sgrep-action#590]
This is happening via both CLI runs and the official semgrep action:

```
Run github/codeql-action/upload-sarif@v2
Uploading results
Error details: instance additionalProperty "fixes" exists in instance when not allowed
Error: Unable to upload "semgrep.sarif" as it is not valid SARIF:
- instance additionalProperty "fixes" exists in instance when not allowed
Error: Unable to upload "semgrep.sarif" as it is not valid SARIF:
- instance additionalProperty "fixes" exists in instance when not allowed
    at validateSarifFileSchema (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:203:15)
    at uploadFiles (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:267:9)
    at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:139:18)
    at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:52:30)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:74:9)
```

Related to #573 

You can see my full workflow run details here:

https://github.com/HariSekhon/GitHub-Actions/runs/6836065996?check_suite_focus=true

**Comment by brendongo** [comment]
@HariSekhon and @mdantonio this should be fixed in https://github.com/returntocorp/semgrep/pull/5425/files and fix will go out on next release

**Comment by mdantonio** [comment]
Great, thank you!

**Comment by HariSekhon** [comment]
@brendongo thanks, will wait for that release, assume it will go into the official action @v1 ?

If that's the case I'll wait for that update and see if all my pipelines and badges across repos clear.

Would you mind posting back here when the new release is cut so I can test it?

**Comment by mdantonio** [comment]
I confirm that now it is working, thank you

**Comment by brendongo** [comment]
Yep it went out with action @v1!

**Comment by brendongo** [comment]
As well as 0.98.0
