### ISSUE TITLE
Should .semgrep folders be scanned by default?

### ISSUE THREAD

**Issue by tkisason** [returntocorp/sgrep-action#72]
I tested out the .semgrep folder rule passing option for the action and it works great. But if you directly copy the rules from semgrep-rules with the accompanying tests, semgrep-action will also scan the .semgrep folder since the default .semgrepignore folder doesn't have this exception. Should this be the default behaviour? 

Anyways, if possible, i vote that by default the .semgrep folder should be under .semgrepignore for the semgrep-action. To help out, i even prepared a pull request: https://github.com/returntocorp/semgrep-action/pull/71 

Thank you!

**Comment by dlukeomalley** [comment]
Thanks for filing @tkisason! @underyx, any thoughts to add?

**Comment by underyx** [comment]
Yeah @tkisason, this makes perfect sense to me! Thanks a lot for the pull request, will merge and release now.

**Comment by underyx** [comment]
All done, thanks again!
