### ISSUE TITLE
Consider returning information about rules that are being run. 

### ISSUE THREAD

**Issue by tkisason** [returntocorp/sgrep-action#74]
Currently semgrep-action will return the number of files that are lined up for scanning, and the number of ignored files, but won't print out the number of rules that are loaded or used (and what is being used to load those rules, registry link, .semgrep or .semgrep.yml):

```
=== detecting environment
| versions    - semgrep 0.25.0 on Python 3.7.9
| environment - running in gitlab-ci, triggering event is 'push'
| semgrep.dev - not logged in
=== setting up agent configuration
| using semgrep rules from the committed .semgrep/ directory
| using path ignore rules from .semgrepignore
| found 100 files in the paths to be scanned
| skipping 5 files based on path ignore rules
=== looking for current issues in 100 files
| 0 current issues found
```

Can we consider if we want to print out the number of rules used in scanning and where the rules have been fetched from?

**Comment by brendongo** [comment]
With 0.86.5 we do print number of rules and where rules are fetched from so marking this as closed

**Comment by tkisason** [comment]
👍  Thank you!
