### ISSUE TITLE
Expose a verbose flag for users

### ISSUE THREAD

**Issue by underyx** [returntocorp/sgrep-action#79]
The hidden `SEMGREP_AGENT_DEBUG` env variable is not exposed to users, we should make this a comfortable public flag instead.

@msorens recommended making it toggleable on the semgrep app's web UI.

## Add to logs

- [ ] `semgrep` should get the `--verbose` flag too and we should pipe its output through

**Comment by jayvdb** [comment]
This would also provide a resolution for https://github.com/returntocorp/semgrep-action/issues/332 .

However, the amount of output from `SEMGREP_AGENT_DEBUG` is huge, and it slows down the runner - too much to usably send to the github action log?

**Comment by brendongo** [comment]
With `semgrep ci` this is now possible by running `semgrep ci --debug` or `semgrep ci --verbose`
