### ISSUE TITLE
Add CI integration for Jenkins

### ISSUE THREAD

**Issue by brampat** [returntocorp/sgrep-action#96]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
Be able to use Semgrep in Jenkins CI, with something like a plugin.

**Describe alternatives you've considered**
Call Semgrep from CLI in Jenkins. This would need the Jenkins server to have Semgrep installed, which in some setups is a lot harder to configure. For instance, if Jenkins runs in distributed on-demand cloud / containers / runtime sandboxes, you would need to configure the install for Semgrep each time a container / runtime sandbox is created and used.

**Additional context**
--

**Comment by dlukeomalley** [comment]
Thank you for filing this ticket @brampat. Moving it over to the semgrep-action repository for now, which should be updated soon to more generically capture Semgrep's CI integrations.

@underyx Any questions for @brampat as we think about how to tackle this and/or if `semgrep_agent` will work out of the box here?

**Comment by dlukeomalley** [comment]
@brampat A Jenkins config was contributed to the docs here: https://semgrep.dev/docs/sample-ci-configs/#jenkins

Does this resolve the spirit of this ticket for you?

**Comment by brendongo** [comment]
`semgrep ci` is runnable wherever we can run a docker container or run pip install so I think this can be closed
