### ISSUE TITLE
Upload SARIF log file

### ISSUE THREAD

**Issue by omerlh** [returntocorp/sgrep-action#97]
Semgrep already supporting SARIF output, it would be nice if the action could just upload the result so it will be shown under the security tab on GitHub

**Comment by dlukeomalley** [comment]
@omerlh Great to see you posting here! This is possible as of today, checkout the Semgrep GitHub Actions documentation for details: https://semgrep.dev/docs/integrations/#continuous-integration-ci

Let me know if you have any other questions. Closing this ticket for now and happy to reopen as needed.

**Comment by omerlh** [comment]
Nice, it wasn't in the repo readme - this is why I missed it.

**Comment by dlukeomalley** [comment]
Ah, good catch. New ticket for that here: https://github.com/returntocorp/semgrep-action/issues/98

I'll make sure it happens this week 👍
